---
- name: Install wgrib2 v3.1.3
  hosts: all
  become: yes
  vars:
    wgrib2_version: "v3.1.3"
    wgrib2_url: "https://www.ftp.cpc.ncep.noaa.gov/wd51we/wgrib2/wgrib2.tgz.{{ wgrib2_version }}"
    install_dir: "/usr/local/wgrib2"
  tasks:
    - name: Install dependencies
      apt:
        name:
          - build-essential
          - gcc
          - gfortran
          - libpng-dev
          - libopenjp2-7-dev
          - zlib1g-dev
          - libnetcdf-dev
          - libproj-dev
          - libgomp1
          - libwebp-dev
          - libzstd-dev
          - curl
          - make
        state: present
      when: ansible_os_family == "Debian"

    - name: Create installation directory
      file:
        path: "{{ install_dir }}"
        state: directory
        mode: '0755'

    - name: Download wgrib2 source code
      get_url:
        url: "{{ wgrib2_url }}"
        dest: "/tmp/wgrib2.tgz"

    - name: Extract source code
      ansible.builtin.unarchive:
        src: "/tmp/wgrib2.tgz"
        dest: "/tmp/"
        remote_src: yes

    - name: Ensure source directory exists
      file:
        path: "/tmp/grib2"
        state: directory
        mode: '0755'

    - name: Ensure config.mk exists before modification
      file:
        path: "/tmp/grib2/config.mk"
        state: touch
        mode: '0644'

    - name: Set environment variables for compilation
      shell: |
        echo "USE_IPOLATES=3" | tee -a /tmp/grib2/config.mk
        echo "USE_SPECTRAL=1" | tee -a /tmp/grib2/config.mk
        echo "USE_PROJ4=1" | tee -a /tmp/grib2/config.mk
        echo "USE_JASPER=0" | tee -a /tmp/grib2/config.mk
        echo "USE_OPENJPEG=1" | tee -a /tmp/grib2/config.mk
        echo "USE_AEC=1" | tee -a /tmp/grib2/config.mk
      args:
        executable: /bin/bash

    - name: Compile wgrib2
      command: make
      args:
        chdir: "/tmp/grib2"
      environment:
        FC: gfortran
        CC: gcc

    - name: Copy wgrib2 binary to /usr/local/bin
      copy:
        src: "/tmp/grib2/wgrib2/wgrib2"
        dest: "/usr/local/bin/wgrib2"
        mode: '0755'
        remote_src: yes

    - name: Copy gmerge to /usr/local/bin
      copy:
        src: "/tmp/grib2/aux_progs/gmerge"
        dest: "/usr/local/bin/"
        mode: '0755'
        remote_src: yes

    - name: Verify installation
      command: wgrib2 --version
      register: wgrib2_version_output
      ignore_errors: yes
      changed_when: false

    - name: Display wgrib2 version
      debug:
        msg: "{{ wgrib2_version_output.stdout }}"
